name: placeholder_Name

on:
  pull_request:
  push:
    branches:
      - branch-1

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        java-version: ['1.8']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'adopt'
        cache: maven

   
    - name: Build with Maven
      run: mvn -B clean install

   
    - name: Set up JDK 1.8 and run codecov bash
      run: |
        bash <(curl -s https://codecov.io/bash)
