name: Java CI with Maven

on:
  push:
    branches: [v5-master]
  pull_request:
    branches: [v5-master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      timeout-minutes: 2 

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
      timeout-minutes: 5 

    - name: Build and skip tests
      run: mvn -B -V -DskipTests=true clean install
      timeout-minutes: 12 

    - name: Run tests with coverage
      run: mvn -B test cobertura:cobertura
      timeout-minutes: 15 

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        verbose: true
      timeout-minutes: 5 # Timeout for this step after 5 minutes
