name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        java-version: [8]
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'adopt'
        cache: 'maven'
    
    - name: Set timezone
      run: echo "TZ=Asia/Shanghai" >> $GITHUB_ENV
    
    - name: Build and Skip Tests
      run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    
    - name: Generate Coverage Report
      run: mvn cobertura:cobertura -Dcobertura.report.format=xml -Dmaven.javadoc.skip=true
    
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true


