name: Java CI with Maven

on:
  push:
    branches: [v5-master] # Run on push to any branch
  pull_request:
    branches: [v5-master] # Run on pull request to any branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      timeout-minutes: 2 

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
      timeout-minutes: 5 

    - name: Build and skip tests
      run: mvn -B -V -DskipTests=true clean install
      timeout-minutes: 5
